{% set version = "2.2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-landscapemetrics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/landscapemetrics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/landscapemetrics/landscapemetrics_{{ version }}.tar.gz
  sha256: b28e3e3782e780cf8bb63dcceeaf5b5cee22ed0409513bfb49db782e59e3a76d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.10
    - r-rcpparmadillo
    - r-cli
    - r-ggplot2
    - r-raster
    - r-sp
    - r-tibble
  run:
    - r-base
    - r-rcpp >=1.0.10
    - r-rcpparmadillo
    - r-cli
    - r-ggplot2
    - r-raster
    - r-sp
    - r-tibble

test:
  commands:
    - $R -e "library('landscapemetrics')"           # [not win]
    - "\"%R%\" -e \"library('landscapemetrics')\""  # [win]

about:
  home: https://r-spatialecology.github.io/landscapemetrics/
  license: GPL-3.0-only
  summary: Calculates landscape metrics for categorical landscape patterns in  a tidy workflow. 'landscapemetrics' reimplements the most common metrics from 'FRAGSTATS' (<https://www.umass.edu/landeco/research/fragstats/fragstats.html>)  and new ones from the current literature on landscape metrics. This package supports
    'raster' spatial objects and takes  RasterLayer, RasterStacks, RasterBricks or lists of RasterLayer from the 'raster' package as input arguments. It further provides utility functions to visualize patches, select metrics and building blocks to develop new  metrics.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Type: Package
# Package: landscapemetrics
# Title: Landscape Metrics for Categorical Map Patterns
# Version: 1.1
# Authors@R: c(person("Maximillian H.K.", "Hesselbarth", role = c("aut", "cre"), email = "maximilian.hesselbarth@uni-goettingen.de", comment = c(ORCID = "0000-0003-1125-9918")), person("Marco", "Sciaini", role = "aut", email = "sciaini.marco@gmail.com", comment = c(ORCID = "0000-0002-3042-5435")), person("Jakub", "Nowosad",  role = "aut", email = "nowosad.jakub@gmail.com",  comment = c(ORCID = "0000-0002-1057-3721")), person("Sebastian", "Hanss",  role = "aut",  comment = c(ORCID = "0000-0002-3990-4897")), person("Laura J.", "Graham", role = "ctb",  comment = "Input on package structure"), person("Jeffrey", "Hollister",  role = "ctb",  comment = "Input on package structure"), person("Kimberly A.", "With",  role = "ctb", comment = "Input on package structure"), person("Florian", "Prive",  role = "ctb",  comment = "Original author of underlying C++ code for get_nearestneighbour() function"),  person("Jeremy", "VanDerWal",  role = "ctb",  comment = "Original author of underlying C code for get_patches() function"),  person("Matt", "Strimas-Mackey",  role = "ctb",  comment = "Bugfix in sample_metrics()") )
# Maintainer: Maximillian H.K. Hesselbarth <maximilian.hesselbarth@uni-goettingen.de>
# Description: Calculates landscape metrics for categorical landscape patterns in  a tidy workflow. 'landscapemetrics' reimplements the most common metrics from 'FRAGSTATS' (<https://www.umass.edu/landeco/research/fragstats/fragstats.html>)  and new ones from the current literature on landscape metrics. This package supports 'raster' spatial objects and takes  RasterLayer, RasterStacks, RasterBricks or lists of RasterLayer from the 'raster' package as input arguments. It further provides utility functions to visualize patches, select metrics and building blocks to develop new  metrics.
# License: GPL-3
# URL: https://r-spatialecology.github.io/landscapemetrics/
# BugReports: https://github.com/r-spatialecology/landscapemetrics/issues
# Depends: R (>= 3.1)
# Imports: cli, crayon, ggplot2, methods, raster, Rcpp, sp, stats, tibble
# Suggests: covr, dplyr, knitr, rgeos, rmarkdown, testthat
# Enhances: stars, sf
# LinkingTo: Rcpp, RcppArmadillo
# ByteCompile: true
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# SystemRequirements: C++11
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-04-25 13:22:25 UTC; Maximilian
# Author: Maximillian H.K. Hesselbarth [aut, cre] (<https://orcid.org/0000-0003-1125-9918>), Marco Sciaini [aut] (<https://orcid.org/0000-0002-3042-5435>), Jakub Nowosad [aut] (<https://orcid.org/0000-0002-1057-3721>), Sebastian Hanss [aut] (<https://orcid.org/0000-0002-3990-4897>), Laura J. Graham [ctb] (Input on package structure), Jeffrey Hollister [ctb] (Input on package structure), Kimberly A. With [ctb] (Input on package structure), Florian Prive [ctb] (Original author of underlying C++ code for get_nearestneighbour() function), Jeremy VanDerWal [ctb] (Original author of underlying C code for get_patches() function), Matt Strimas-Mackey [ctb] (Bugfix in sample_metrics())
# Repository: CRAN
# Date/Publication: 2019-04-25 13:50:03 UTC
